# Site settings
title: Jonathan Hardison
description: 'Crazy Man Cage'
url: 'http://www.jonathanhardison.com'
baseurl: '/'
google_analytics: 'UA-73380426-1'
bing_verify: A80D6529E57BAE1CA8C5185C522957CA
disqus_shortname: 'jonathanhardison'

author:
  name: 'Jonathan Hardison'
  twitter_username: jhardison
  github_username:  jmhardison
  gitlab_username:  jmhardison
  linkedin_username:  jonathanhardison
  twitch_username: RyudenPhoenix

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor', 'config.ru']
