trigger:
- master

resources:
  - repo: self
    fetchDepth: 1

#jobs to do dev or prod builds
jobs:
  - job: BuildStage
    pool:
      name: 'Hosted Ubuntu 1604'
    workspace:
      clean: all
    steps:
    - task: Docker@0
      displayName: 'Run Jekyll'
      inputs:
        containerRegistryType: 'Container Registry'
        action: 'Run an image'
        imageName: 'jekyll/builder:latest'
        volumes: |
          $(build.sourcesDirectory):/srv/jekyll
          $(build.sourcesDirectory)/_site:/srv/jekyll/_site
        containerCommand: 'jekyll build --future'
        detached: false
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(build.sourcesDirectory)' 
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'zipfile'
        targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: ReleaseStage
    pool:
      name: 'Hosted Ubuntu 1604'
    workspace:
      clean: all
    dependsOn: BuildStage
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) #master
    variables:
      - group: Firebase
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'zipfile'
        targetPath: '$(build.sourcesDirectory)'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(Build.BuildId).zip' 
        destinationFolder: '$(build.sourcesDirectory)/extract'
        cleanDestinationFolder: true
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'install firebase-tools'
    - task: Bash@3
      inputs:
        targetType: inline
        script: 'firebase deploy --token $(fb_ci_token) --project $(fb_projectid) --message "Release: $(Build.BuildId)"'
        workingDirectory: '$(build.sourcesDirectory)/extract'

