source 'https://rubygems.org'
#ruby '2.3.3'
#gem 'json', github: 'flori/json', branch: 'v1.8'
#gem 'github-pages', '~> 133'
#gem 'html-proofer', '~> 3.6'
gem 'jekyll'
gem 'jekyll-paginate'
#gem 'RedCloth'